"""add missing fields to users, matches, games

Revision ID: ea4c46d692f0
Revises: b752f62926a5
Create Date: 2025-10-03 13:51:14.547437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4c46d692f0'
down_revision: Union[str, Sequence[str], None] = 'b752f62926a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('frame_number', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('game_type', sa.Enum('EIGHT_BALL', 'NINE_BALL', 'TEN_BALL', name='gametype'), nullable=False))
    op.add_column('matches', sa.Column('race_to', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'display_name')
    op.drop_column('matches', 'race_to')
    op.drop_column('matches', 'game_type')
    op.drop_column('games', 'frame_number')
    # ### end Alembic commands ###
